set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_VERSION 10.0)
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES NUVIO_WINDOWS_TRIPLE)

if(NOT DEFINED NUVIO_WINDOWS_TRIPLE)
    message(FATAL_ERROR "NUVIO_WINDOWS_TRIPLE must select an llvm-mingw target")
endif()

set(NUVIO_LLVM_MINGW_ROOT "/opt/llvm-mingw" CACHE PATH "llvm-mingw root")
set(NUVIO_LLVM_MINGW_BIN "${NUVIO_LLVM_MINGW_ROOT}/bin")
set(CMAKE_C_COMPILER "${NUVIO_LLVM_MINGW_BIN}/${NUVIO_WINDOWS_TRIPLE}-clang")
set(CMAKE_CXX_COMPILER "${NUVIO_LLVM_MINGW_BIN}/${NUVIO_WINDOWS_TRIPLE}-clang++")
set(CMAKE_RC_COMPILER "${NUVIO_LLVM_MINGW_BIN}/${NUVIO_WINDOWS_TRIPLE}-windres")
set(CMAKE_AR "${NUVIO_LLVM_MINGW_BIN}/llvm-ar")
set(CMAKE_RANLIB "${NUVIO_LLVM_MINGW_BIN}/llvm-ranlib")
set(CMAKE_STRIP "${NUVIO_LLVM_MINGW_BIN}/llvm-strip")

set(CMAKE_FIND_ROOT_PATH "${NUVIO_LLVM_MINGW_ROOT}/${NUVIO_WINDOWS_TRIPLE}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
